default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:  <%= ENV["POSTGRES_PASSWORD"] %>
  timeout: 5000
  host: localhost
  port: 5432

development:
  <<: *default
  database: denuncia_ciudadana_dev

test:
  <<: *default
  database: denuncia_ciudadana_test

production:
  url: <%= ENV["DATABASE_URL"] %>
